### ISSUE TITLE
Windows build is failing

### ISSUE THREAD

**Issue by likewei92** [conda-forge/gmsh-feedstock#24]
It seems like it can't find an icon file? https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=106636&view=logs&j=2cc45e14-23e3-52d7-b33a-8c2744410b97&t=21c44aa7-1ae3-5312-cacc-7f19fefc82f4&l=2900

**Comment by likewei92** [comment]
Could one of the maintainers help to take a look at the issue? :P @guyer @isuruf @looooo @xywei

**Comment by guyer** [comment]
I've filed a [gmsh issue](https://gitlab.onelab.info/gmsh/gmsh/issues/735) and will do some experimenting in the meantime
