### ISSUE TITLE
Why is there gmsh AND python-gmsh?

### ISSUE THREAD

**Issue by JoostGevaert** [conda-forge/gmsh-feedstock#30]
Hello,
Thanks for providing the Python API for Gmsh on conda-forge!
It was quite confusing to me however, that the conda package gmsh doesn't install the Python module gmsh.py directly. I was therefore using `pip install gmsh` inside my conda env for quite a long time, before finally finding out about this feedstock (also because I didn't know about feedstocks ect...).
What is the reason for providing Gmsh on conda-forge in two separate packages?
Joost

**Comment by isuruf** [comment]
Because there are people who don't need the python API and the dependencies it pulls in.

**Comment by JoostGevaert** [comment]
Thanks for the reply!
Christophe Geuzaine from Gmsh was quite surprised to learn that Gmsh is on conda-forge:
https://gitlab.onelab.info/gmsh/gmsh/-/issues/870

Would it be an idea to provide a link on the [gmsh anaconda cloud page](https://anaconda.org/conda-forge/gmsh) to this feedstock, or make it more obvious in another way that `conda install gmsh` does not provide the gmsh Python API?

**Comment by isuruf** [comment]
Maybe you can add a sentence to the summary at https://github.com/conda-forge/gmsh-feedstock/blob/master/recipe/meta.yaml#L91
Can you make that change and send a PR?

**Comment by JoostGevaert** [comment]
Sure!
