### ISSUE TITLE
windows package is missing HXT algorithm

### ISSUE THREAD

**Issue by adrianinsaval** [conda-forge/gmsh-feedstock#66]
https://github.com/conda-forge/gmsh-feedstock/blob/d0f4772d8f85838ad91ba44d9386b05a078138f9/recipe/bld_gmsh.bat#L17

is there a reason for this? this is problematic for use with FreeCAD as some workbenches try to use this algorithm: https://forum.freecadweb.org/viewtopic.php?p=643764#p643764

**Comment by looooo** [comment]
maybe try to create a PR, changing this value. Then we see why it wasn't enabled.
